### ISSUE TITLE
Managed action bar

### ISSUE THREAD

**Issue by ZhaoTzuHsien** [pixerena/firework#8]
Bukkit and Adventure's API have poor support for action bar. In future release, we will create a new UI component that let users extend to create managed action bar.

## TODO
- [x] Reactive action bar
- [x] Permanant action bar
- [x] Player-scoped action bar
- [x] Javadoc

## Resources
- https://www.spigotmc.org/threads/permanent-action-bar.378270/
